spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/minibank
    username: minibank
    password: minibank123
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
